apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-chart.fullname" . }}
  labels: {{- include "echo-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "echo-chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
