apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: probe-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: probe-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
