apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Pod
metadata:
  name: tools
  namespace: dev
spec:
  containers:
    - name: main
      image: registry.k8s.io/busybox
      args: ["sleep","3600"]
      env: [{ name: LOG_LEVEL, value: "debug" }]
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
