apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: viewer-binding
  namespace: secure-ns
subjects:
  - kind: ServiceAccount
    name: default
    namespace: secure-ns
roleRef:
  kind: Role
  name: viewer
  apiGroup: rbac.authorization.k8s.io
