namePrefix: dev-
commonLabels:
  env: dev
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: echo
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/containers/0/resources/limits
        value: { cpu: "200m", memory: "256Mi" }
