apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels: { app: echo }
spec:
  replicas: 2
  selector:
    matchLabels: { app: echo }
  template:
    metadata:
      labels: { app: echo }
    spec:
      containers:
        - name: echoserver
          image: registry.k8s.io/echoserver:1.4
          ports: [{ containerPort: 8080 }]
          readinessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 3
